# Generated by Django 3.1.7 on 2021-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='date_invited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
