# Generated by Django 3.1.2 on 2020-10-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('number_of_words', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('expected_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_received', models.IntegerField(blank=True, default=0, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
