# Generated by Django 3.1.2 on 2020-10-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='person',
            field=models.CharField(choices=[('Bery', 'Bery'), ('Muema', 'Muema'), ('Jose', 'Jose')], max_length=100),
        ),
    ]
