# Generated by Django 3.1.2 on 2020-10-27 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workrecords', '0002_auto_20201017_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonChoises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfWorkChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('person', models.CharField(choices=[('Bery', 'Bery'), ('Muema', 'Muema'), ('Jose', 'Jose')], max_length=100)),
                ('type_of_work', models.CharField(default='Writing', max_length=100)),
                ('pages', models.IntegerField(default=0)),
                ('number_of_words', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('expected_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=True)),
                ('amount_received', models.IntegerField(blank=True, default=0, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workrecords.work')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
