# Generated by Django 3.1.2 on 2020-10-27 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workrecords', '0004_auto_20201027_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordofwork',
            name='user',
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
