# Generated by Django 3.1.2 on 2020-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0006_auto_20201027_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='title',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='work',
            name='person',
            field=models.CharField(max_length=100),
        ),
    ]
