# Generated by Django 3.1.3 on 2021-02-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0007_auto_20201028_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order_number',
            field=models.CharField(default='#00000', max_length=200),
        ),
    ]
