# Generated by Django 3.1.7 on 2021-03-24 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0008_work_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='personchoises',
            name='email',
            field=models.EmailField(default='person@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='personchoises',
            name='phone',
            field=models.IntegerField(default='0700500600'),
        ),
        migrations.AddField(
            model_name='work',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workrecords.personchoises'),
        ),
        migrations.AddField(
            model_name='work',
            name='category_of_work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workrecords.typeofworkchoices'),
        ),
        migrations.AddField(
            model_name='work',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
