# Generated by Django 3.1.7 on 2021-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0009_auto_20210324_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
