# Generated by Django 3.1.7 on 2021-03-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0010_auto_20210324_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workrecords.personchoises'),
        ),
        migrations.AlterField(
            model_name='work',
            name='category_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workrecords.typeofworkchoices'),
        ),
        migrations.AlterField(
            model_name='work',
            name='person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='type_of_work',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
