# Generated by Django 3.1.7 on 2021-03-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0011_auto_20210324_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='person',
        ),
        migrations.RemoveField(
            model_name='work',
            name='type_of_work',
        ),
    ]
