# Generated by Django 3.1.7 on 2021-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0013_auto_20210405_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
