# Generated by Django 3.1.7 on 2021-04-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20210410_1812'),
        ('workrecords', '0015_auto_20210410_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_from_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teams.team'),
        ),
    ]
