# Generated by Django 3.1.7 on 2021-04-10 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workrecords', '0016_work_is_from_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.AlterField(
            model_name='work',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='authentication.user'),
        ),
        migrations.DeleteModel(
            name='RecordOfWork',
        ),
    ]
