# Generated by Django 3.1.7 on 2021-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0017_auto_20210410_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
